[project]
name = "applied-ai-challenges"
version = "0.1.0"
description = "Weekly challenges for U of Hull Applied AI module"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "notebook>=7.3.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
]
